-- MySQL Script generated by MySQL Workbench
-- Mon Sep 16 14:35:01 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pedidoitens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedidoitens` (
  `idpedidoitens` INT NOT NULL,
  `qtdade` INT NULL,
  `preco` FLOAT NULL,
  `total` FLOAT NULL,
  `pedidos_idpedidos` INT NULL,
  `produtos_idprodutos` INT NULL,
  PRIMARY KEY (`idpedidoitens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `idprodutos` INT NOT NULL,
  `dsproduto` VARCHAR(45) NULL,
  `preco` FLOAT NULL,
  `qtdade` INT NULL,
  `foto` LONGBLOB NULL,
  `categoria_idcategoria` INT NULL,
  `` VARCHAR(45) NULL,
  `pedidoitens_idpedidoitens` INT NOT NULL,
  PRIMARY KEY (`idprodutos`),
  INDEX `fk_produtos_pedidoitens1_idx` (`pedidoitens_idpedidoitens` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_pedidoitens1`
    FOREIGN KEY (`pedidoitens_idpedidoitens`)
    REFERENCES `mydb`.`pedidoitens` (`idpedidoitens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT NOT NULL,
  `dscategoria` VARCHAR(45) NOT NULL,
  `produtos_idprodutos` INT NOT NULL,
  PRIMARY KEY (`idcategoria`),
  INDEX `fk_categoria_produtos_idx` (`produtos_idprodutos` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_produtos`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `mydb`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `idpedido` INT NOT NULL,
  `data` DATE NULL,
  `status` VARCHAR(45) NULL,
  `sessao` VARCHAR(45) NULL,
  `clientes_idclientes` INT NULL,
  `pedidoitens_idpedidoitens` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_pedidoitens1_idx` (`pedidoitens_idpedidoitens` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_pedidoitens1`
    FOREIGN KEY (`pedidoitens_idpedidoitens`)
    REFERENCES `mydb`.`pedidoitens` (`idpedidoitens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idclientes` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `sessao` VARCHAR(45) NULL,
  `clientes_idclientes` INT NULL,
  `pedido_idpedido` INT NOT NULL,
  PRIMARY KEY (`idclientes`),
  INDEX `fk_clientes_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `mydb`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
